### ISSUE TITLE
ValueError: You need to supply the callbackType to remove it  App:3.0.4-3098 Plugin:3.0.11-30

### ISSUE THREAD

**Issue by weiweihuanghuang** [weiweihuanghuang/ShowCrosshairOnSelect#1]
```
Details:
Traceback (most recent call last):

  File "plugin.py", line 304, in willDeactivate
    Glyphs.removeCallback(self.mouseDidMove_, MOUSEMOVED)

  File "GlyphsApp/GlyphsApp/__init__.py", line 1440, in __removeCallback__

ValueError: You need to supply the callbackType to remove it

App:3.0.4-3098 Plugin:3.0.11-30
```
@schriftgestalt ?

**Comment by schriftgestalt** [comment]
You can ignore this.
